#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = pipewire 
exec-once = waybar
exec-once = mako
exec-once = nm-applet
exec-once = hyprpaper
exec-once = hypridle

# buat cek low bat dan kasih notification
# exec-once = bash -c 'while true; do ~/.local/scripts/battery-check.sh; sleep 30; done'


